[package]
name = "coptrs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "coptrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.3"}
